title: PoleFX Docs
description: PoleFX Docs
remote_theme: just-the-docs/just-the-docs@v0.9.0
# theme: just-the-docs
url: https://spencerhochberg.github.io
logo: "assets/img/POLEFX_LOGO_w_color_trans_250.png"
color_scheme: dark

# Custom auxiliary links
aux_links:
  "Visit PoleFX Website": 
    - "https://polefx.com"  

collections:
  docs:
    output: true


sass:
  sass_dir: _sass
  style: compressed  # optional

